---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

data<-read.csv("repdata_data_activity/activity.csv")

# Change date format into date
data$date<-as.Date(data$date)

 day\n(NA removed)")
------------------------------------------       
## What is mean total number of steps taken per day?

# total number of steps
sum_steps<-aggregate(data$steps,by=list(data$date),FUN=sum,na.rm=TRUE) 

hist(sum_steps$x, 
      breaks=seq(from=0, to=25000, by=2500),
      col="yellow", 
      xlab="Total number of steps", 
      ylim=c(0, 20), 
      main="Histogram of the total number of steps taken each

# mean of steps is 9354.23
mean(sum_steps$x)

# median of steps is 10395
median(sum_steps$x)
------------------------------------------      
## What is the average daily activity pattern?

# Time series plot of the average number of steps taken
avg_steps<-aggregate(data$steps,by=list(data$interval),FUN=mean,na.rm=TRUE)
colnames(avg_steps)<-c("interval","steps")
library(ggplot2)
ggplot(aes(x=interval,y=steps),data=avg_steps)+geom_line()

# 5-minute interval that, on average, contains the maximum number of steps is 835
avg_steps[avg_steps$steps==max(avg_steps$steps),1]
------------------------------------------      
## Imputing missing values
# total number of missing values in the dataset (i.e. the total number of rows with NA’s) is 2304
sum(is.na(data$steps))

# Replace NA values with the mean of the steps
data$steps[is.na(data$steps)]<-mean(data$steps,na.rm=TRUE)

# Histogram with Repaced values
sum_steps<-aggregate(data$steps,by=list(data$date),FUN=sum,na.rm=TRUE) 

hist(sum_steps$x, 
      breaks=seq(from=0, to=25000, by=2500),
      col="yellow", 
      xlab="Total number of steps", 
      ylim=c(0, 30), 
      main="Total number of steps taken each day\n(NA replaced by mean)")
# mean after replacing values is 10766.19     
mean(sum_steps$x) 
# median after replacing values is 10766.19    
median(sum_steps$x)
------------------------------------------          
## Are there differences in activity patterns between weekdays and weekends?
# Convert date into weekdays

data$days=tolower(weekdays(data$date))

# categorise of days into weekend and weekdays

data$day_type<-ifelse(data$days=="saturday"|data$days=="sunday","weekend","weekday")

# mean steps taken on weekend or weekday in the intervals
avg_steps<-aggregate(data$steps,by=list(data$interval,data$day_type),FUN=mean,na.rm=TRUE)

colnames(avg_steps)<-c("interval","day_type","steps")

# panel plot between average steps and interval seperated by day type
ggplot(aes(x=interval,y=steps),data=avg_steps)+geom_line()+facet_wrap(~avg_steps$day_type)
------------------------------------------        
